### PR TITLE
Allow extension of JS modules in addition to JSON objects.

### PR DESCRIPTION
**Pull request by nprbst**
This is useful (to me) for building a layered configuration modules incorporating both primitives and functions.

Here's an example to illustrate...
#### base-config.js

``` js
module.exports = (function() {
    var self = {
        company: {
            name: 'DEFAULT'
        },
        copyright: {
            year: '2011',
            message: function () {
                return 'Copyright ' + self.copyright.year + ' by ' + self.company.name + '. All rights reserved.';
            }
        }
    }
    return self;
})();
```
#### override-config.js

``` js
module.exports = (function() {
    var self = {
        company: {
            name: 'SomeCo'
        },
        copyright: {
            year: '2013'
        }
    }
    return self;
})();
```
#### Gruntfile.js

``` js
grunt.initConfig({
  extend: {
    options: {
      require: true
    },
    extendedConfig: {
      files: {
        'resulting-config.js': ['base-config.js,', 'override-config.js']
      }
    }
  }
});
```
#### resulting-config.js

``` js
module.exports = (function() {
    var self = {
        company: {
            name: 'SomeCo'
        },
        copyright: {
            year: '2013',
            message: function () {
                return 'Copyright ' + self.copyright.year + ' by ' + self.company.name + '. All rights reserved.';
            }
        }
    }
    return self;
})();
```
#### app.js

``` js
require('resulting-config.js').copyright.message(); // Copyright 2013 by SomeCo. All rights reserved.
```

### CODE REVIEW

**Comment by grancalavera** [comment]
Hi Nathan

I'm glad you are finding grunt-extend useful. I've been thinking about your suggestion for the last couple of days and I've come to think that it somehow diverges from the original intention of grunt-extend. I wrote this plugin with the intention to provide a regular way to use JavaScript objects as the input for generating JSON files solely. 

Although I have found cases where I need a function as part of the configuration for something else, I still think that the solution for those cases should lie outside grunt-extend. One such case is configuring [grunt-contrib-handlebars](https://github.com/gruntjs/grunt-contrib-handlebars), where `processContent`, `processAST`, `processName` and `processPartialName` are all functions. That's one case where grunt-extend isn't really useful and another solution needs to be found for at least portions of the configuration. In cases like this, generating dynamic tasks or using global config options in the Gruntfile might prove useful.

Another situation where you might want to be able to deal with functions is generation `main.js` files to be consumed by [require.js](http://requirejs.org/). At the root of the file you will find [a function that takes a single object as argument](http://requirejs.org/docs/api.html#data-main).  It is possible to generate the argument object using grunt-extend, but it is not possible to express the function in JSON. In cases like this one, I'd recommend to write a template file, and leave a placeholder for your configuration, generate the `main.js` file and let the config function consume and process your JSON file. The template would look something like this:

``` js
/* global require */
'use strict';
require.config(<%= config %>)
```

Then you can use [grunt.template](http://gruntjs.com/api/grunt.template) to process the template using your JSON file as part of the `data` option:

``` js
var config = grunt.file.readJSON('config.json')
var template = grunt.file.read('main-template.js')
var mainjs = grunt.template.process(template, { data: { config: config } })
grunt.file.write('main.js', mainjs)
```

On a setup like this, `config.json` would be the output of a series of configuration extensions handled by grunt-extend, and the config function would manipulate the data in any required way. This has the advantage of keeping state and behaviour separated, both in the plugins you are using and in your workflow. You can use the same state to generate different behaviour, for instance, using the same configuration to generate documentation for your project and to generate deployment files.

I hope this explains my position regarding grunt-extend. I'll be really glad to know what do you think.

L.

**Comment by nprbst** [comment]
I appreciate the well-reasoned response to my PR. I understand the desire to purely focus on JSON, and that makes sense. However, I'm already using my fork of grunt-extend in production, so I'll be maintaining it and pulling in your upstream changes to stay current. How about we leave this PR open for awhile and see what comments accumulate?

Nathan

**Comment by grancalavera** [comment]
Yup, makes sense. I'll keep it open for a while.

**Comment by grancalavera** [comment]
I'm closing this now.

**Pull request closed without merging**
